name: Build CV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build PDF
      env:
        CV_EMAIL: ${{ secrets.CV_EMAIL }}
        CV_PHONE: ${{ secrets.CV_PHONE }}
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: output/kozuch_cv.pdf
        retention-days: 30
