name: Build CV

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended
        
    - name: Build PDF
      env:
        CV_EMAIL: ${{ secrets.CV_EMAIL }}
        CV_PHONE: ${{ secrets.CV_PHONE }}
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: output/kozuch_cv.pdf
        retention-days: 30
        
    - name: Create Release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: output/kozuch_cv.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
